# Generated by Django 5.2.10 on 2026-01-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbuspass',
            name='location',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
