# Generated by Django 5.2.10 on 2026-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0002_studentbuspass_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularbuspass',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentbuspass',
            name='age',
        ),
        migrations.AddField(
            model_name='regularbuspass',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='studentbuspass',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
