# Generated by Django 5.2.10 on 2026-01-26 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0003_remove_regularbuspass_age_remove_studentbuspass_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularbuspass',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularbuspass',
            name='payment_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='regularbuspass',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentbuspass',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentbuspass',
            name='payment_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='studentbuspass',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
