# Generated by Django 5.2.10 on 2026-01-26 12:36

import buspass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0005_renewalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalrequest',
            name='buspass_id',
        ),
        migrations.AddField(
            model_name='regularbuspass',
            name='epass_id',
            field=models.CharField(default=buspass.models.generate_epass_id, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='renewalrequest',
            name='epass_id',
            field=models.CharField(default='EPB-0000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentbuspass',
            name='epass_id',
            field=models.CharField(default=buspass.models.generate_epass_id, max_length=10, unique=True),
        ),
    ]
