# Generated by Django 5.2.10 on 2026-01-26 13:04

import buspass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0006_remove_renewalrequest_buspass_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularbuspass',
            name='expiry_date',
            field=models.DateField(default=buspass.models.one_month_expiry),
        ),
        migrations.AddField(
            model_name='studentbuspass',
            name='expiry_date',
            field=models.DateField(default=buspass.models.one_month_expiry),
        ),
    ]
