# Generated by Django 5.2.10 on 2026-01-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0007_regularbuspass_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalrequest',
            name='epass_id',
        ),
        migrations.AddField(
            model_name='renewalrequest',
            name='pass_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Regular', 'Regular')], default='Student', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renewalrequest',
            name='regular_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buspass.regularbuspass'),
        ),
        migrations.AddField(
            model_name='renewalrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewalrequest',
            name='student_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buspass.studentbuspass'),
        ),
    ]
