# Generated by Django 5.2.10 on 2026-01-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0008_remove_renewalrequest_epass_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalrequest',
            name='pass_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Regular', 'Regular')], default='Student', max_length=10),
        ),
    ]
