# Generated by Django 5.2.10 on 2026-01-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0009_alter_renewalrequest_pass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalrequest',
            name='pass_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Regular', 'Regular')], max_length=10),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
