# Generated by Django 5.2.10 on 2026-01-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0010_alter_renewalrequest_pass_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
