# Generated by Django 5.2.10 on 2026-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0011_renewalrequest_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
