# Generated by Django 5.2.10 on 2026-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0012_alter_renewalrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularbuspass',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='renewalrequest',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='studentbuspass',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='regularbuspass',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentbuspass',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
