# Generated by Django 5.2.10 on 2026-01-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0013_remove_regularbuspass_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequest',
            name='payment_token2',
            field=models.UUIDField(null=True),
        ),
    ]
